workflows:
  ios-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Delete and regenerate iOS folder
        script: |
          rm -rf ios
          flutter create --platforms=ios .
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - smqubedoc@gmail.com
