workflows:
  ios-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Delete and regenerate iOS folder
        script: |
          rm -rf ios
          flutter create --platforms=ios .
          flutter pub get
      - name: Update iOS platform and add Firebase fix
        script: |
          cd ios
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile
          sed -i '' "/flutter_additional_ios_build_settings(target)/a\\
                config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          " Podfile
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - smqubedoc@gmail.com
